### ISSUE TITLE
connexion offline

### ISSUE THREAD

**Issue by SlyderSlash-SNAGE** [Elodie-S/salle-de-jim#1]
Bonjour,

Votre connexion est offline - page introuvable,
il faudrait les remettre en fonctionnement @Elodie-S

**Comment by Elodie-S** [comment]
Bonjour,
effectivement, Heroku semble ne pas reconnaitre le chemin d'accès à l'application. 
Je vais rajouter un fichier README.md pour pouvoir tester l'application en local.

**Comment by SlyderSlash-SNAGE** [comment]
Je vous conseille de mettre un fichier SQL car la connexion à la base de donnée peut être bloqué par aws
